---
title: Ulysses' trip
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: UlyssesZhan@gmail.com
description: Here we are at the awesome (awful) blog written by Ulysses Zhan!
copyright: 2020 Ulysses Zhan
baseurl: ''
url: https://UlyssesZh.github.io
header_pages:
- my_pages/about.md
- my_pages/archives.html
- my_pages/contact.md
- my_pages/friends.md
theme: minima
future: true
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-archives
exclude:
- LICENSE.md
- README.md
- Gemfile
- Gemfile.lock
- ".git/"
- ".idea/"
- ".rubocop.yml"
- publish.sh
measurement_id: G-7TSJ5VM6YC
google_verification: ZuV45Knwuwl49Nvh9UsDzniZ-3qy3bGhBPofLK3SZPw
tagmanager_id: GTM-5PX967D
twitter_username: UlyssesZhan
github_username: UlyssesZh
facebook_username: YouqiuZhan
instagram_username: ulysseszhan
pinterest_username: ulysseszhan
jekyll-archives:
  enabled: all
  layout: archive
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: tag-category-archive
    tag: tag-category-archive
  permalinks:
    year: "/archives/:year/"
    month: "/archives/:year/:month/"
    day: "/archives/:year/:month/:day/"
    tag: "/archives/tag/:name/"
    category: "/archives/category/:name/"
rpg-map:
  enabled:
  - test
