name: Deploy to master

on:
  push:
    branches:
      - development

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Jekyll
        uses: fabacab/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.JEKYLL_PAT }}
          pre_build_commands: gem install bundler
          git_committer_email: 2938747508@qq.com
          git_committer_name: Ulysses Zhan
